/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedCostSettingsRouteImport } from './routes/_authenticated/cost-settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedGrandAccountsRouteImport } from './routes/_authenticated/grand-accounts'
import { Route as AuthenticatedInstallationsRouteImport } from './routes/_authenticated/installations'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPartsRouteImport } from './routes/_authenticated/parts'
import { Route as AuthenticatedQuoteRemindersRouteImport } from './routes/_authenticated/quote-reminders'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedStorageLocationsRouteImport } from './routes/_authenticated/storage-locations'
import { Route as AuthenticatedSubcontractorsRouteImport } from './routes/_authenticated/subcontractors'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedInstallationInstallationSlugRouteImport } from './routes/_authenticated/installation.$installationSlug'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes.index'
import { Route as AuthenticatedQuotesQuoteIdRouteImport } from './routes/_authenticated/quotes.$quoteId'
import { Route as AuthenticatedQuotesNewRouteImport } from './routes/_authenticated/quotes.new'
import { Route as AuthenticatedSiteSiteSlugRouteImport } from './routes/_authenticated/site.$siteSlug'
import { Route as AuthenticatedStockTicketsLocationIdRouteImport } from './routes/_authenticated/stock-tickets.$locationId'
import { Route as AuthenticatedSuppliersSupplierIdRouteImport } from './routes/_authenticated/suppliers.$supplierId'
import { Route as AuthenticatedTicketTicketSlugRouteImport } from './routes/_authenticated/ticket.$ticketSlug'
import { Route as ApiWebhooksTokenRouteImport } from './routes/api.webhooks.$token'
import { Route as ApiImportsInstallationsTokenRouteImport } from './routes/api.imports.installations.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostSettingsRoute =
  AuthenticatedCostSettingsRouteImport.update({
    id: '/cost-settings',
    path: '/cost-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrandAccountsRoute =
  AuthenticatedGrandAccountsRouteImport.update({
    id: '/grand-accounts',
    path: '/grand-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstallationsRoute =
  AuthenticatedInstallationsRouteImport.update({
    id: '/installations',
    path: '/installations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartsRoute = AuthenticatedPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuoteRemindersRoute =
  AuthenticatedQuoteRemindersRouteImport.update({
    id: '/quote-reminders',
    path: '/quote-reminders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStorageLocationsRoute =
  AuthenticatedStorageLocationsRouteImport.update({
    id: '/storage-locations',
    path: '/storage-locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubcontractorsRoute =
  AuthenticatedSubcontractorsRouteImport.update({
    id: '/subcontractors',
    path: '/subcontractors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedInstallationInstallationSlugRoute =
  AuthenticatedInstallationInstallationSlugRouteImport.update({
    id: '/installation/$installationSlug',
    path: '/installation/$installationSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesQuoteIdRoute =
  AuthenticatedQuotesQuoteIdRouteImport.update({
    id: '/quotes/$quoteId',
    path: '/quotes/$quoteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesNewRoute = AuthenticatedQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiteSiteSlugRoute =
  AuthenticatedSiteSiteSlugRouteImport.update({
    id: '/site/$siteSlug',
    path: '/site/$siteSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockTicketsLocationIdRoute =
  AuthenticatedStockTicketsLocationIdRouteImport.update({
    id: '/stock-tickets/$locationId',
    path: '/stock-tickets/$locationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersSupplierIdRoute =
  AuthenticatedSuppliersSupplierIdRouteImport.update({
    id: '/$supplierId',
    path: '/$supplierId',
    getParentRoute: () => AuthenticatedSuppliersRoute,
  } as any)
const AuthenticatedTicketTicketSlugRoute =
  AuthenticatedTicketTicketSlugRouteImport.update({
    id: '/ticket/$ticketSlug',
    path: '/ticket/$ticketSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiWebhooksTokenRoute = ApiWebhooksTokenRouteImport.update({
  id: '/api/webhooks/$token',
  path: '/api/webhooks/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportsInstallationsTokenRoute =
  ApiImportsInstallationsTokenRouteImport.update({
    id: '/api/imports/installations/$token',
    path: '/api/imports/installations/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/contracts': typeof AuthenticatedContractsRoute
  '/cost-settings': typeof AuthenticatedCostSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/grand-accounts': typeof AuthenticatedGrandAccountsRoute
  '/installations': typeof AuthenticatedInstallationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/quote-reminders': typeof AuthenticatedQuoteRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/storage-locations': typeof AuthenticatedStorageLocationsRoute
  '/subcontractors': typeof AuthenticatedSubcontractorsRoute
  '/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/installation/$installationSlug': typeof AuthenticatedInstallationInstallationSlugRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/site/$siteSlug': typeof AuthenticatedSiteSiteSlugRoute
  '/stock-tickets/$locationId': typeof AuthenticatedStockTicketsLocationIdRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/ticket/$ticketSlug': typeof AuthenticatedTicketTicketSlugRoute
  '/api/webhooks/$token': typeof ApiWebhooksTokenRoute
  '/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/api/imports/installations/$token': typeof ApiImportsInstallationsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/contracts': typeof AuthenticatedContractsRoute
  '/cost-settings': typeof AuthenticatedCostSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/grand-accounts': typeof AuthenticatedGrandAccountsRoute
  '/installations': typeof AuthenticatedInstallationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/quote-reminders': typeof AuthenticatedQuoteRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/storage-locations': typeof AuthenticatedStorageLocationsRoute
  '/subcontractors': typeof AuthenticatedSubcontractorsRoute
  '/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/installation/$installationSlug': typeof AuthenticatedInstallationInstallationSlugRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/site/$siteSlug': typeof AuthenticatedSiteSiteSlugRoute
  '/stock-tickets/$locationId': typeof AuthenticatedStockTicketsLocationIdRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/ticket/$ticketSlug': typeof AuthenticatedTicketTicketSlugRoute
  '/api/webhooks/$token': typeof ApiWebhooksTokenRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/api/imports/installations/$token': typeof ApiImportsInstallationsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/cost-settings': typeof AuthenticatedCostSettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/grand-accounts': typeof AuthenticatedGrandAccountsRoute
  '/_authenticated/installations': typeof AuthenticatedInstallationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/parts': typeof AuthenticatedPartsRoute
  '/_authenticated/quote-reminders': typeof AuthenticatedQuoteRemindersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/storage-locations': typeof AuthenticatedStorageLocationsRoute
  '/_authenticated/subcontractors': typeof AuthenticatedSubcontractorsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/installation/$installationSlug': typeof AuthenticatedInstallationInstallationSlugRoute
  '/_authenticated/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/_authenticated/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/_authenticated/site/$siteSlug': typeof AuthenticatedSiteSiteSlugRoute
  '/_authenticated/stock-tickets/$locationId': typeof AuthenticatedStockTicketsLocationIdRoute
  '/_authenticated/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/_authenticated/ticket/$ticketSlug': typeof AuthenticatedTicketTicketSlugRoute
  '/api/webhooks/$token': typeof ApiWebhooksTokenRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/api/imports/installations/$token': typeof ApiImportsInstallationsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/contracts'
    | '/cost-settings'
    | '/dashboard'
    | '/docs'
    | '/grand-accounts'
    | '/installations'
    | '/orders'
    | '/parts'
    | '/quote-reminders'
    | '/settings'
    | '/sites'
    | '/storage-locations'
    | '/subcontractors'
    | '/suppliers'
    | '/tickets'
    | '/webhooks'
    | '/clients/$clientId'
    | '/installation/$installationSlug'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/site/$siteSlug'
    | '/stock-tickets/$locationId'
    | '/suppliers/$supplierId'
    | '/ticket/$ticketSlug'
    | '/api/webhooks/$token'
    | '/quotes/'
    | '/api/imports/installations/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/contracts'
    | '/cost-settings'
    | '/dashboard'
    | '/docs'
    | '/grand-accounts'
    | '/installations'
    | '/orders'
    | '/parts'
    | '/quote-reminders'
    | '/settings'
    | '/sites'
    | '/storage-locations'
    | '/subcontractors'
    | '/suppliers'
    | '/tickets'
    | '/webhooks'
    | '/clients/$clientId'
    | '/installation/$installationSlug'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/site/$siteSlug'
    | '/stock-tickets/$locationId'
    | '/suppliers/$supplierId'
    | '/ticket/$ticketSlug'
    | '/api/webhooks/$token'
    | '/quotes'
    | '/api/imports/installations/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/contracts'
    | '/_authenticated/cost-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/docs'
    | '/_authenticated/grand-accounts'
    | '/_authenticated/installations'
    | '/_authenticated/orders'
    | '/_authenticated/parts'
    | '/_authenticated/quote-reminders'
    | '/_authenticated/settings'
    | '/_authenticated/sites'
    | '/_authenticated/storage-locations'
    | '/_authenticated/subcontractors'
    | '/_authenticated/suppliers'
    | '/_authenticated/tickets'
    | '/_authenticated/webhooks'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/installation/$installationSlug'
    | '/_authenticated/quotes/$quoteId'
    | '/_authenticated/quotes/new'
    | '/_authenticated/site/$siteSlug'
    | '/_authenticated/stock-tickets/$locationId'
    | '/_authenticated/suppliers/$supplierId'
    | '/_authenticated/ticket/$ticketSlug'
    | '/api/webhooks/$token'
    | '/_authenticated/quotes/'
    | '/api/imports/installations/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiWebhooksTokenRoute: typeof ApiWebhooksTokenRoute
  ApiImportsInstallationsTokenRoute: typeof ApiImportsInstallationsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cost-settings': {
      id: '/_authenticated/cost-settings'
      path: '/cost-settings'
      fullPath: '/cost-settings'
      preLoaderRoute: typeof AuthenticatedCostSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grand-accounts': {
      id: '/_authenticated/grand-accounts'
      path: '/grand-accounts'
      fullPath: '/grand-accounts'
      preLoaderRoute: typeof AuthenticatedGrandAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/installations': {
      id: '/_authenticated/installations'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof AuthenticatedInstallationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts': {
      id: '/_authenticated/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof AuthenticatedPartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quote-reminders': {
      id: '/_authenticated/quote-reminders'
      path: '/quote-reminders'
      fullPath: '/quote-reminders'
      preLoaderRoute: typeof AuthenticatedQuoteRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage-locations': {
      id: '/_authenticated/storage-locations'
      path: '/storage-locations'
      fullPath: '/storage-locations'
      preLoaderRoute: typeof AuthenticatedStorageLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subcontractors': {
      id: '/_authenticated/subcontractors'
      path: '/subcontractors'
      fullPath: '/subcontractors'
      preLoaderRoute: typeof AuthenticatedSubcontractorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/installation/$installationSlug': {
      id: '/_authenticated/installation/$installationSlug'
      path: '/installation/$installationSlug'
      fullPath: '/installation/$installationSlug'
      preLoaderRoute: typeof AuthenticatedInstallationInstallationSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/$quoteId': {
      id: '/_authenticated/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AuthenticatedQuotesQuoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/new': {
      id: '/_authenticated/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedQuotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site/$siteSlug': {
      id: '/_authenticated/site/$siteSlug'
      path: '/site/$siteSlug'
      fullPath: '/site/$siteSlug'
      preLoaderRoute: typeof AuthenticatedSiteSiteSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-tickets/$locationId': {
      id: '/_authenticated/stock-tickets/$locationId'
      path: '/stock-tickets/$locationId'
      fullPath: '/stock-tickets/$locationId'
      preLoaderRoute: typeof AuthenticatedStockTicketsLocationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/$supplierId': {
      id: '/_authenticated/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AuthenticatedSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthenticatedSuppliersRoute
    }
    '/_authenticated/ticket/$ticketSlug': {
      id: '/_authenticated/ticket/$ticketSlug'
      path: '/ticket/$ticketSlug'
      fullPath: '/ticket/$ticketSlug'
      preLoaderRoute: typeof AuthenticatedTicketTicketSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/webhooks/$token': {
      id: '/api/webhooks/$token'
      path: '/api/webhooks/$token'
      fullPath: '/api/webhooks/$token'
      preLoaderRoute: typeof ApiWebhooksTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imports/installations/$token': {
      id: '/api/imports/installations/$token'
      path: '/api/imports/installations/$token'
      fullPath: '/api/imports/installations/$token'
      preLoaderRoute: typeof ApiImportsInstallationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedSuppliersRouteChildren {
  AuthenticatedSuppliersSupplierIdRoute: typeof AuthenticatedSuppliersSupplierIdRoute
}

const AuthenticatedSuppliersRouteChildren: AuthenticatedSuppliersRouteChildren =
  {
    AuthenticatedSuppliersSupplierIdRoute:
      AuthenticatedSuppliersSupplierIdRoute,
  }

const AuthenticatedSuppliersRouteWithChildren =
  AuthenticatedSuppliersRoute._addFileChildren(
    AuthenticatedSuppliersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedCostSettingsRoute: typeof AuthenticatedCostSettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedGrandAccountsRoute: typeof AuthenticatedGrandAccountsRoute
  AuthenticatedInstallationsRoute: typeof AuthenticatedInstallationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPartsRoute: typeof AuthenticatedPartsRoute
  AuthenticatedQuoteRemindersRoute: typeof AuthenticatedQuoteRemindersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedStorageLocationsRoute: typeof AuthenticatedStorageLocationsRoute
  AuthenticatedSubcontractorsRoute: typeof AuthenticatedSubcontractorsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRouteWithChildren
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRoute
  AuthenticatedInstallationInstallationSlugRoute: typeof AuthenticatedInstallationInstallationSlugRoute
  AuthenticatedQuotesQuoteIdRoute: typeof AuthenticatedQuotesQuoteIdRoute
  AuthenticatedQuotesNewRoute: typeof AuthenticatedQuotesNewRoute
  AuthenticatedSiteSiteSlugRoute: typeof AuthenticatedSiteSiteSlugRoute
  AuthenticatedStockTicketsLocationIdRoute: typeof AuthenticatedStockTicketsLocationIdRoute
  AuthenticatedTicketTicketSlugRoute: typeof AuthenticatedTicketTicketSlugRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedCostSettingsRoute: AuthenticatedCostSettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedGrandAccountsRoute: AuthenticatedGrandAccountsRoute,
  AuthenticatedInstallationsRoute: AuthenticatedInstallationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPartsRoute: AuthenticatedPartsRoute,
  AuthenticatedQuoteRemindersRoute: AuthenticatedQuoteRemindersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedStorageLocationsRoute: AuthenticatedStorageLocationsRoute,
  AuthenticatedSubcontractorsRoute: AuthenticatedSubcontractorsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRouteWithChildren,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRoute,
  AuthenticatedInstallationInstallationSlugRoute:
    AuthenticatedInstallationInstallationSlugRoute,
  AuthenticatedQuotesQuoteIdRoute: AuthenticatedQuotesQuoteIdRoute,
  AuthenticatedQuotesNewRoute: AuthenticatedQuotesNewRoute,
  AuthenticatedSiteSiteSlugRoute: AuthenticatedSiteSiteSlugRoute,
  AuthenticatedStockTicketsLocationIdRoute:
    AuthenticatedStockTicketsLocationIdRoute,
  AuthenticatedTicketTicketSlugRoute: AuthenticatedTicketTicketSlugRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiWebhooksTokenRoute: ApiWebhooksTokenRoute,
  ApiImportsInstallationsTokenRoute: ApiImportsInstallationsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
