ALTER TABLE public.contracts
  ADD COLUMN IF NOT EXISTS on_call_included BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS repairs_included BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS on_call_hourly_rate NUMERIC,
  ADD COLUMN IF NOT EXISTS on_call_travel_fee NUMERIC,
  ADD COLUMN IF NOT EXISTS shipping_fee NUMERIC,
  ADD COLUMN IF NOT EXISTS waste_treatment_fee NUMERIC,
  ADD COLUMN IF NOT EXISTS lifting_equipment_fee NUMERIC;

ALTER TABLE public.quotes
  ADD COLUMN IF NOT EXISTS intervention_reason TEXT NOT NULL DEFAULT 'standard_repair',
  ADD COLUMN IF NOT EXISTS is_on_call BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS shipping_fee NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS waste_treatment_fee NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lifting_equipment_fee NUMERIC NOT NULL DEFAULT 0;
